nerp/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IS.Sess;
using IS.uni;
using IS.fitframework;
using IS.localcomm;
using System.IO;
namespace uni.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
        session ses = new session();
        localcommonlib com = new localcommonlib();
//        public ActionResult Index()
//        {
////            uni.Models.CommonMessage obj = new Models.CommonMessage();
//            //obj.link = ses.targetpage;
//            //obj.message = ses.inform;
//            //obj.title = ses.title;
//            //obj.waiting = 1000;// ses.waitingtime;
//            //return View(obj);
//        }
        /// <summary>
        /// Hiển thị phần login hoặc yêu cầu login trong trang chính
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            bool isLoged = (!string.IsNullOrEmpty(ses.loginName));
            ViewBag.isloged = isLoged;
            if (isLoged)
            {
                ViewBag.loginImg = string.IsNullOrEmpty(ses.loginImg) ? "noimage.jpg" : ses.loginImg;
                ViewBag.staffname = ses.STAFF.NAME;
                ViewBag.staffdepartmentname = ses.STAFF.DEPARTMENTNAME;
                string img = ses.STAFF.IMG;
                if (string.IsNullOrEmpty(img))
                {
                    img = "/sysimage/logo.jpg";//default is the logo of department
                }
                ViewBag.staffima = img;
            }
            return PartialView();

        }


        public ActionResult Tabmenu()
        {

            if (ses.loginName == "")
            {
                Response.Redirect("/staff/login");
            }
            ViewBag.loginname = ses.loginFullName;
            //List<string> st = new List<string>();
            //st.Add("Menu1");
            //st.Add("Menu2");
            //st.Add("Menu3");
            //SYSMENU_BUS bus = new SYSMENU_BUS();
            //List<SYSMENU_OBJ> li = bus.getAdmin(ses.gUNIVERSITYCODE,ses.getFunctionList());
            //bus.CloseConnection();
            return View();
        }
        public ActionResult Menu()
        {
            SYSMENU_BUS bus = new SYSMENU_BUS();
            string functionlist = ses.getFunctionList();
            List<SYSMENU_OBJ> li = bus.getAdmin(ses.gUNIVERSITYCODE,functionlist);
            foreach (SYSMENU_OBJ obj in li)
            {
                if(string.IsNullOrEmpty(obj.ICON))
                {
                    obj.ICON = "fa-circle-o";
                }
            }
            bus.CloseConnection();
            return View(li);

        }
        public ActionResult MasterTitle()
        {
            ViewBag.title = "Hệ thống hỗ trợ dạy và học tiếng Nga";
            return View();

        }
        /// <summary>
        /// Lấy danh menu của sinh viên
        /// </summary>
        /// <returns></returns>
        public ActionResult Menustudent()
        {
            SYSMENU_BUS bus = new SYSMENU_BUS();
            List<SYSMENU_OBJ> li = bus.getStudent(ses.gUNIVERSITYCODE, ses.getFunctionList());
            bus.CloseConnection();
            return View(li);

        }
        public ActionResult TopMenu()
        {
            SYSMENU_BUS bus = new SYSMENU_BUS();
            List<SYSMENU_OBJ> li = bus.getAdminTop(ses.gUNIVERSITYCODE, ses.getFunctionList());
            bus.CloseConnection();
            return View(li);

        }

        //cho bản chạy ngoài
        //public ActionResult Menu()
        //{
        //    if (ses.loginName == "")
        //    {
        //        Response.Redirect("/staff/login");
        //    }
        //    //ViewBag.loginname = ses.loginFullName;
        //    //List<string> st = new List<string>();
        //    //st.Add("Menu1");
        //    //st.Add("Menu2");
        //    //st.Add("Menu3");
        //    SYSMENU_BUS bus = new SYSMENU_BUS();
        //    List<SYSMENU_OBJ> li = bus.getAdmin(ses.gUNIVERSITYCODE, ses.getFunctionList());
        //    bus.CloseConnection();
        //    return View(li);
        //}
        public ActionResult FontendMenu()
        {
            SYSMENU_BUS bus = new SYSMENU_BUS();
            List<SYSMENU_OBJ> li = bus.getAdmin(ses.gUNIVERSITYCODE, ses.getFunctionList());
            bus.CloseConnection();
            return View(li);
        }
        public ActionResult Header()
        {
            bool isLoged = (ses.isLogin()==0);
            ViewBag.isloged = isLoged;
            ViewBag.departmentname = ses.loginDepartmentName;
            ViewBag.loginname = ses.loginFullName;
            ViewBag.loginImg = string.IsNullOrEmpty(ses.loginImg) ? "Content/sysimage/noimage.png" : ses.loginImg;
            if (!System.IO.File.Exists(Server.MapPath("/") +  ViewBag.loginImg))
            {
                ViewBag.loginImg = "noimage.jpg";
            }
            return View();
        }
        public ActionResult Task()
        {
            bool isLoged = (ses.isLogin() == 0);
            ViewBag.isloged = isLoged;
            TASKNOTE_BUS bus = new TASKNOTE_BUS();
            List<TASKNOTE_OBJ> li = new List<TASKNOTE_OBJ>();
            if (isLoged)
            {
                int countpage=0;
                li=bus.getAllBy2("eventtime desc",10,1, out countpage, new fieldpara("staffcode", ses.loginCode, paraType.VARCHAR,(int)searchType.NONE,1,(int)combineType.OR) , new fieldpara("staffcode", "", paraType.VARCHAR, (int)searchType.NONE, 1, (int)combineType.OR));
                bus.CloseConnection();
            }
           
            ViewBag.list = li;
            return View();
        }
        public ActionResult Headerstudent()
        {
            bool isLoged = (!string.IsNullOrEmpty(ses.loginName));
            ViewBag.isloged = isLoged;

            ViewBag.loginname = ses.loginFullName;
            ViewBag.loginImg = string.IsNullOrEmpty(ses.loginImg) ? "noimage.jpg" : ses.loginImg;
            if (!System.IO.File.Exists(Server.MapPath("/") + "Files/" + ViewBag.loginImg))
            {
                ViewBag.loginImg = "noimage.jpg";
            }
            return View();
        }
        public ActionResult Header2()
        {
            ViewBag.loginname = ses.loginFullName;
            ViewBag.loginImg = string.IsNullOrEmpty(ses.loginImg) ? "noimage.jpg" : ses.loginImg;
            return View();
        }
        public ActionResult FontendHeader()
        {
            return View();
        }
        public ActionResult FontendFooter()
        {
            return View();
        }
        public ActionResult Footer()
        {
            return View();
        }
        public ActionResult RightConfig()
        {
            return View();
        }
        /// <summary>
        /// Hỗ trợ việc upload file từ client lên server
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult post()
        {
            COMMONTOOL comto = new COMMONTOOL();
            string[] imgexts = { "BMP", "JPG", "PNG", "GIF", "JPEG", "TIF" };
            string[] docexts = { "PDF", "ZIP", "RAR", "7Z", "GZ", "GZIP" };
            string filename = "";
            string linkfile = "";
            string uploadedfilename = "";
            string ext = "";
            int ret = 0;
            string basepath = "";
            int type = 0;
            //must be logined
            if (ses.isLogin() != 0)
            {
                //ret = -1;
            }
            if (Request.Files.Count < 1)
            {
                ret = -2;
            }
            if (ret >= 0)
            {
                //only the first file
                uploadedfilename = Request.Files[0].FileName;
                ext = com.fileExtension(uploadedfilename);
                ext = ext.ToUpper();
                if (imgexts.Contains(ext))
                {
                    type = 1;
                }
                if (docexts.Contains(ext))
                {
                    type = 2;
                }
                if (type == 0)
                {
                    ret = -3;//Không thuộc kiểu file được chấp nhận
                }

            }
            //upload limmit
            if (ret >= 0)
            {
                if (type == 1 && Request.Files[0].ContentLength > 20 * 1048576)
                {
                    Request.Files[0].InputStream.Dispose();
                    ret = -5;
                }
                if (type == 2 && Request.Files[0].ContentLength > 40 * 1048576)
                {
                    Request.Files[0].InputStream.Dispose();
                    ret = -5;

                }
            }
            if (ret >= 0)
            {
                //tính đường dẫn file lưu
                basepath = Server.MapPath("/");
                if (type == 1)
                {
                    linkfile = string.Format("images/{0}/{1}/", DateTime.Now.Year, DateTime.Now.Month.ToString("00"));
                    basepath += linkfile;

                }
                else
                {
                    linkfile = string.Format("files/{0}/{1}/", DateTime.Now.Year, DateTime.Now.Month.ToString("00"));
                    basepath += linkfile;
                }
                com.createDirectory(basepath);
            }
            if (ret >= 0)
            {
                var fileContent = Request.Files[0];
                filename = com.checkFileName(basepath, fileContent.FileName);
                if (filename != "")
                {
                    linkfile = "/" + linkfile + filename;
                    var stream = fileContent.InputStream;
                    // and optionally write the file to disk
                    try
                    {
                        var fileStream = System.IO.File.Create(basepath + filename);
                        stream.CopyTo(fileStream);

nerp/Views/Shared/AdminIndex.cshtml
@{
    ViewBag.Title = "Hệ thống dạy, học và thi trực tuyến";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="container">
    <div class="loading-page full-parrent center" id="loading-page" style="width:100%">
        <div class="center full-parrent" style="width:100%;text-align:center;">
            Loading............
        </div>
    </div>
</div>
<script type="text/javascript">
    var _objectfromserver = @Html.Raw(ViewBag.defaultvalue);
    function getDefaultFromServer()
    {
        return  _objectfromserver;
    }
</script>
@section scripts {
<link href="~/Content/customcss/custom.css" rel="stylesheet" />
    <script src="~/Scripts/Inform.js"></script>
    @foreach (var item in ViewBag.jsx)
        {
        <script src="@item"></script>
    }

}

nerp/Views/Shared/StudentIndex.cshtml
@{
    ViewBag.Title = "Hệ thống dạy, học và thi trực tuyến";
    Layout ="~/Views/Shared/_LayoutStudent.cshtml";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<div id="container">
    <div class="loading-page full-parrent center" id="loading-page" style="width:100%">
        <div class="center full-parrent" style="width:100%;text-align:center;">
            Loading............
        </div>
    </div>
</div>
<script type="text/javascript">
    var _objectfromserver = @Html.Raw(ViewBag.defaultvalue);
    function getDefaultFromServer()
    {
        return  _objectfromserver;
    }
</script>
@section scripts {
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<link href="~/Content/customcss/custom.css" rel="stylesheet" />
    <script src="~/Scripts/Inform.js"></script>
    @foreach (var item in ViewBag.jsx)
    {
        <script src="@item"></script>
    }
}

nerp/Views/Shared/_LayoutStudent.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Online testing system - 2017</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link href="~/Content/Ionicons/css/ionicons.min.css" rel="stylesheet" />
    <!-- DataTables -->
    <link href="~/Content/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/jquery/jquery-ui.min.css" rel="stylesheet" />

    <!-- Theme style -->
    <link href="~/Content/AdminLTE/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- AdminLTE Skins. -->
    <link href="~/Content/AdminLTE/css/skins/_all-skins.min.css" rel="stylesheet" />
    @*React select *@
    <link href="~/Content/reactselect/react-select.css" rel="stylesheet" />
    <link href="~/Scripts/Dropdowntree/dropdowntree.css" rel="stylesheet" />

    <link href="~/Content/comboxtree/css/default/style.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Content/sysimage/favicon.ico" type="image/x-icon">
    <link href="~/Content/site.css" rel="stylesheet" />
    

</head>
<body class="skin-green sidebar-mini sidebar-collapse ">
    <div class="wrapper">
        <header class="main-header">
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top navbar-fixed-top" style="margin-left:0">
                <a href="/" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><img src="~/Content/sysimage/logo.png" height="auto" width="50px" /></span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>m</b>ERP</span>
                </a>
                @*Thiết lập tiêu đề, sau này sẽ sử dụng file cấu hình để thiết lập*@
                @Html.Action("MasterTitle", "Common")
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @Html.Action("Task", "Common")
                        @Html.Action("Header", "Common")
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Action("Menu", "Common")

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- Main content -->
            <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
            <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
            <script src="~/Scripts/respond.js"></script>
            <script src="~/Scripts/install.js"></script>
            <script src="~/Scripts/mediaDevices-getUserMedia-polyfill.js"></script>
            <section class="content" style="padding-top: 0 ">
                @RenderBody()
                <button id="return-to-top">
                    <span class="glyphicon glyphicon-chevron-up">
                    </span>
                </button>
                <!-- /.row -->
            </section>
            <!-- /.content -->
            <!-- /.content-wrapper -->
        </div>
        <section class="main-footer no-print">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2017
            </div>
            <strong>Copyright &copy; 2014-2017 <a href="https://fit.mta.edu.vn">Faculty of Information Technology</a>/Military Technical Academy .</strong> All rights
            reserved.
        </section>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script>
        var globalApp;
        function getApp(ev) {
            globalApp = ev;
        }
    </script>
    <script>
        //when you click this
        function clickFunction(id) {
            var question = $("#" + id);
            question.empty();
            var x = document.getElementById(id).length;
            console.log(x);
            //var questiongroupcode = id.split("_")[0];
            var questioncode = id.split("_")[1];
            // var questiontype = id.split("_")[2];
            $.ajax({
                url: "/StudentExam/GetAnswerQuestionFf",
                data: {questioncode},
                dataType:'json',
                success: function (data) {
                    if (!!data.listAnswerObjs) {
                        $("#"+id).get(0).options.length = 0;
                        $("#" + id).get(0).options[0] = new Option("(Chọn đáp án đúng)", "");
                        setTimeout(function () {
                            data.listAnswerObjs.map(function (item) {
                                $('#'+id).append('<option value='+item.CODE+'>'+item.NAME+'</option>');
                            }.bind(this));
                        }, 50);
                        $('#' + id).attr('onclick', '').unbind('click');
                        $('#' + id).attr("onchange", "myChangeFunction('"+id+"')");
                    }
                }.bind(this),
                error: function (xhr, status, err) {
                    console.log(err.toString());
                }
            });
        }
        function myChangeFunction(id) {
            var questioncode = id.split('_')[1];
            var type = id.split('_')[2];
            var answercode = document.getElementById(id).value;
            console.log(answercode);
            globalApp.onCheck(questioncode, answercode, type);
        }
    </script>
    <script src="~/Scripts/jquery/jquery.min.js">
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <!-- SlimScroll -->
    <script src="~/Scripts/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Scripts/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Scripts/AdminLTE/js/adminlte.min.js"></script>
    <script src="~/Scripts/comboxtree/js/jstree.min.js"></script>
    <script src="~/Scripts/tree/custom.tree.js"></script>
    <script src="~/Content/moment/moment.min.js"></script>
    <script src="~/Content/bootbox/bootbox.min.js"></script>
    <script src="~/Scripts/react/react.js"></script>
    <script src="~/Scripts/react/react-dom.js"></script>
    <script src="~/Scripts/func.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    @RenderSection("scripts", false)
    <!-- page script -->

    <script>
        function dragstart_handler(event) {
            //debugger
            //$('#' + event.target.id).draggable({
            //    revert: true
            //});
            //     event.target.style.opacity = .5;
            // Add the target element's id to the data transfer object
            if (!!event) {
                event.dataTransfer.setData("text", event.target.id);
                event.dropEffect = "move";
            }
        }
        //Cho phép thả vào đây hay không
        function dragover_handler(event) {
            ///    console.log("dragover",event.target);
            event.preventDefault();
            // Set the dropEffect to move
            event.dataTransfer.dropEffect = "move";
        }
        ///vị trí thả
        //sự kiện ondrop ở đây
        //global dai dien cho event.target.id sau khi bat dau duoc keo roi khoi vi tri
        function drop_handler(event) {
            //event.target.style.background = "";
            //console.log("droptarget", event.target);
            //console.log("currentdroptarget", event.currentTarget);
            ///trước khi cho phép thả 1 element hay không thì cần phải xác định được xem element
            //hiện tại đã có element con nào kéo vào đấy hay chưa
            //việc này rất quan trọng vì tránh trường hợp thả nhiều hơn 1 element vào 1 vị trí
            //tìm số lượng element trong nó
            if (!!global) {
                event.preventDefault();
                var type = global.split('_')[3];
                var answercode = global.split('_')[1];
                //lay questiongroup cua vi tri dang duoc drops
                var targetdraggroupcode = global.split('_')[0];
                //lay questiongroup cua vi tri dang duoc drag
                /// targerdrop questiongroupcode_questioncode_type
                var targetdrop = event.currentTarget.id;
                var targetdropgroupcode = targetdrop.split('_')[0];
                //kiem tra neu hop le có nghĩa là 2 questiongroup === nhau thì chúng cùng 1 group
                //-> cho phép tranferdata
                // if (targetdropgroupcode === targetdraggroupcode && childCount < 1) {
                if (targetdropgroupcode === targetdraggroupcode) {
                    //check any p tag inside
                    var el = event.currentTarget.getElementsByTagName("p");
                    var data = event.dataTransfer.getData("text");
                    if (el.length === 0) {
                        event.currentTarget.appendChild(document.getElementById(data));
                    } else {
                        var cut = el[0].id.split('_')[1];
                        document.getElementById(el[0].id.replace("_" + cut, "")).appendChild(el[0]);
                        event.currentTarget.appendChild(document.getElementById(data));
                    }
                    event.preventDefault();
                    //var data = event.dataTransfer.getData("text");
                    //event.target.appendChild(document.getElementById(data));
                    //hiện tại thì chỉ xử lý được đến thế này
                    //vấn đề kĩ thuật trong khâu kéo thả cần xem xét lại
                    var questioncode = targetdrop.split('_')[1];
                    globalApp.onCheck(questioncode, answercode, type);

                } else {
                    log.show("Không thể thực hiện được thao tác này", false);
                }
            }

        }
    </script>

    <script>
        (function() {
            if (document.domain !== "localhost")
            {
                $("body").css({
                    "-webkit-user-select": "none",
                    "-moz-user-select": "-moz-none",
                    "-ms-user-select": "none",
                    "user-select": "none"
                });
            }
        })();
    </script>
    <script>
        //first of all,we need to get the following input id {id}
        //then get questiontype{FG,FI} and questiongroup{QG_id_[FG|FI]}
        function myFunction(id) {
            ///the value after onfoucusout the input
            if (!!document.getElementById(id).value) {
                //nội dung câu trả lời của câu hỏi dạng FG điền từ vào đoạn trống
                var value = document.getElementById(id).value;
                var income = id.split("_");
                //lấy kiểu của câu trả lời
                var questiontype = income[2];
                //lấy mã của câu hỏi
                var questioncode = income[1];
                // var questiongroup = income[0];
                globalApp.onCheck(questioncode, value, questiontype);

            }
        }
    </script>
<script>
    // ===== Scroll to Top ====
    $(window).scroll(function () {
        if ($(this).scrollTop() >= 50) {        // If page is scrolled more than 50px
            $('#return-to-top').fadeIn(200);    // Fade in the arrow
        } else {
            $('#return-to-top').fadeOut(200);   // Else fade out the arrow
        }
    });
    $('#return-to-top').click(function () {      // When arrow is clicked
        $('body,html').animate({
            scrollTop: 0                       // Scroll to top of body
        }, 1500);
    });
</script>
<script>
    // SORTABLE
    $(function () {
        $("#abc").sortable();
    });
</script>
    
<script>
    //recording support

</script>
    

</body>
</html>